config/routes.rb
VideoStreaming::Application.routes.draw do
  root :to => "rooms#index"

  resources :rooms do
    collection do
      get :record
      get :sizing
    end
  end

  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get

end

app/models/room.rb
class Room < ActiveRecord::Base
   attr_accessible :name , :public, :sessionId
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.where(:public => true).order("created_at DESC").limit(10)
    @new_room = Room.new
  end

  def create
    config_opentok
    session = @opentok.create_session request.remote_addr
    params[:room][:sessionId] = session.session_id

    @new_room = Room.new(params[:room])

    respond_to do |format|
      if @new_room.save
        format.html { redirect_to("/party/"+@new_room.id.to_s) }
      else
        format.html { render :controller => 'rooms', :action => "index" }
      end
    end
  end

  def party
    @room = Room.find(params[:id])

    config_opentok

    @tok_token = @opentok.generate_token :session_id => @room.sessionId
  end

  def record
    @room = Room.first
    config_opentok
    @tok_token = @opentok.generate_token :session_id => @room.sessionId
  end

  def sizing
    @room = Room.first
    config_opentok
    @tok_token = @opentok.generate_token :session_id => @room.sessionId
  end

  private

  def config_opentok
    if @opentok.nil?
      @opentok = OpenTok::OpenTokSDK.new '22262222', "504037a81d8fc4d2263404db1e852498f34a7ce3"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
require 'date'

module RoomsHelper

  def start_diff(date)
    intervals = [["day", 1], ["hour", 24], ["minute", 60], ["second", 60]]
    elapsed = DateTime.now - DateTime.parse(date.to_s)
    #tense = elapsed > 0 ? "since" : "until"
    #event = elapsed > 0 ? "the Video Party started" : "the Video Party starts"
    interval = 1.0
    parts = intervals.collect do |name, new_interval|
      interval /= new_interval
      number, elapsed = elapsed.abs.divmod(interval)
    "#{number.to_i} #{name}#{"s" unless number == 1}"
    end
    "#{parts.join(", ")} ago."
  end


end

app/views/home/index.html.erb
<div id="invitation">Invite your friends! Share the url of this page http://opentok-videoparty.heroku.com/party/<%= @room.id %></div>
<div id="videobox">

</div>
<script src="http://static.opentok.com/v0.91/js/TB.min.js" type="text/javascript"></script>
<script type="text/javascript">
var apiKey = 366872;
var sessionId = "<%= @room.sessionId %>";
var token = "<%= @tok_token %>";

var session;

TB.addEventListener('exception', exceptionHandler);
session = TB.initSession(sessionId);

//Video chat event listeners
session.addEventListener('sessionConnected', sessionConnectedHandler);
session.addEventListener('streamCreated', streamCreatedHandler);
    session.addEventListener('streamDestroyed', streamDestroyedHandler);

session.connect(apiKey, token);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoParty</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1>Video Party</h1>
      <h3>[Start or join a video party, invite your friends but most of all have fun!]</h3>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      &copy; 2011, Melih Onvural - Distributed under MIT License
    </div>
  </div>
</body>
</html>

app/views/rooms/_form.html.erb
<fieldset>
<legend>Start a new party room</legend>
<%= form_for(@new_room) do |f| %>
Party Name: <%= f.text_field :name %><br/><br/>
Public? <%= f.check_box :public %><br/><br/>

<%= f.submit %>
<% end %>
</fieldset>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div id="newRoom">
<%= render 'rooms/form' %>
</div>

<fieldset>
<legend>Existing party rooms</legend>
<table cellpadding="2" cellspacing="5">
  <tr>
    <th>Name</th>
    <th>Started</th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td align="center" width="300px"><a href="/party/<%= room.id %>"><%= room.name %></a></td>
    <td><%= start_diff(room.created_at) %></td>
  </tr>
<% end %>
</table>
</fieldset>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/party.html.erb
<div id="invitation">Invite your friends! Share the url of this page http://opentok-videoparty.heroku.com/party/<%= @room.id %></div>
<div id="videobox">

</div>
<div id="myPublisherDiv" ></div>
<script src='http://static.opentok.com/v1.1/js/TB.min.js' type="text/javascript"></script>
<script type="text/javascript">
var apiKey = '22262222';
//var sessionId = "2_MX4yMjIzMjM0Mn4xMjcuMC4wLjF-TW9uIERlYyAyNCAyMzozMjo0MSBQU1QgMjAxMn4wLjQ5NzE5NDIzfg";
//var token = "T1==cGFydG5lcl9pZD0yMjIzMjM0MiZzaWc9ZDJiOWFiZDExMDM0ZTY2M2Q0MTRiMzE5OGVlYjZhMDY4ZTRmOTZkOTpzZXNzaW9uX2lkPTJfTVg0eU1qSXpNak0wTW40eE1qY3VNQzR3TGpGLVRXOXVJRVJsWXlBeU5DQXlNem96TWpvME1TQlFVMVFnTWpBeE1uNHdMalE1TnpFNU5ESXpmZyZjcmVhdGVfdGltZT0xMzU2NDIwNzc5JmV4cGlyZV90aW1lPTEzNTY1MDcxNzkmcm9sZT1wdWJsaXNoZXImY29ubmVjdGlvbl9kYXRhPSZub25jZT0xNzYzODI=";
var sessionId = "<%= @room.sessionId %>";
var token = "<%= @tok_token %>";

function subscribeToStreams( streams ) {
  for(var i= 0; i < streams.length; i++) {
    var stream = streams[i];
    if(session.connection.connectionId == stream.connection.connectionId ) {
      return;
    }
    var div = document.createElement('div');
    var divId = 'stream-'+stream.streamId;
    div.setAttribute('id', divId);
    document.body.appendChild( div );
    session.subscribe( stream, divId, {width: '900', height: '400', mirror: false } );
  }
}

function sessionConnectedHandler(sessionConnectedEvent ) {
  alert('connected');
  session.publish(publisher);
  subscribeToStreams( sessionConnectedEvent.streams)
}

function streamCreatedHandler( streamCreatedEvent ) {
  subscribeToStreams( streamCreatedEvent.streams );
}
var publisher = TB.initPublisher(apiKey, 'myPublisherDiv', {width: '500', height: '400'});
//var publisher = TB.initPublisher(apiKey, 'myPublisherDiv', { publishVideo: false });

//TB.addEventListener('exception', exceptionHandler);
var session = TB.initSession(sessionId);

//Video chat event listeners

session.addEventListener('streamCreated', streamCreatedHandler);
session.addEventListener('sessionConnected', sessionConnectedHandler);
//session.addEventListener('streamDestroyed', streamDestroyedHandler);

session.connect(apiKey, token);
</script>

app/views/rooms/record.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>OpenTok API Sample &#8212; Stand-Alone Archives</title>
	<link href="http://static.opentok.com/opentok/assets/css/demos.css" type="text/css" rel="stylesheet" >
	<script src="http://static.opentok.com/v1.1/js/TB.min.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		var recorderManager;
		var recorder;
		var player;
		var recImgData;

		var API_KEY = "22232342"; // Replace with your API key. See https://dashboard.tokbox.com/projects
		var TOKEN = "<%= @tok_token %>"; // Replace with a generated token that has the moderator role. See https://dashboard.tokbox.com/projects

		var VIDEO_HEIGHT = 240;
		var VIDEO_WIDTH = 320;

		// Un-comment either of the following to set automatic logging and exception handling.
		// See the exceptionHandler() method below.
		// TB.setLogLevel(TB.DEBUG);
		// TB.addEventListener('exception', exceptionHandler);

		function init() {
			recorderManager = TB.initRecorderManager(API_KEY);
			createRecorder();
		}

		function createRecorder() {
			var recDiv = document.createElement('div');
			recDiv.setAttribute('id', 'recorderElement');
			document.getElementById('recorderContainer').appendChild(recDiv);
			recorder = recorderManager.displayRecorder(TOKEN, recDiv.id);
			recorder.addEventListener('recordingStarted', recStartedHandler);
			recorder.addEventListener('archiveSaved', archiveSavedHandler);
		}

		function getImg(imgData) {
			var img = document.createElement('img');
			img.setAttribute('src', 'data:image/png;base64,' + imgData);
			return img;
		}

		function loadArchiveInPlayer(archiveId) {
			if (!player) {
				playerDiv = document.createElement('div');
				playerDiv.setAttribute('id', 'playerElement');
				document.getElementById('playerContainer').appendChild(playerDiv);
				player = recorderManager.displayPlayer(archiveId, TOKEN, playerDiv.id);
				document.getElementById('playerContainer').style.display = 'block';
			} else {
				player.loadArchive(archiveId);
			}
		}

		//--------------------------------------
		//  OPENTOK EVENT HANDLERS
		//--------------------------------------

		function recStartedHandler(event) {
			recImgData = recorder.getImgData();
		}

		function archiveSavedHandler(event) {
			document.getElementById('archiveList').style.display = 'block';
			var aLink = document.createElement('a');
			aLink.setAttribute('href',
								"javascript:loadArchiveInPlayer(\'" + event.archives[0].archiveId + "\')");
			var recImg = getImg(recImgData);
			recImg.setAttribute('style', 'width:80; height:60; margin-right:2px');
			aLink.appendChild(recImg);
			document.getElementById('archiveList').appendChild(aLink);
		}

		function archiveLoadedHandler(event) {
			archive = event.archives[0];
			archive.startPlayback();
		}

		/*
		If you un-comment the call to TB.addEventListener('exception', exceptionHandler) above, OpenTok calls the
		exceptionHandler() method when exception events occur. You can modify this method to further process exception events.
		If you un-comment the call to TB.setLogLevel(), above, OpenTok automatically displays exception event messages.
		*/
		function exceptionHandler(event) {
			alert('Exception: ' + event.code + '::' + event.message);
		}

	</script>
	</head>
	<body onload="init()">
		<div id="recorderContainer" style="float:left; height:340px; width 329px; margin-right:8px;">
			<p>Recorder:</p>
		</div>
		<div id="playerContainer" style="float:left; height:340px; width 320px; display:none">
			<p>Stand-alone player:</p>
		</div>
		<div style="clear:both; margin"></div>
		<div id="archiveList" style="height:100px; display:none">
			<p>Recordings (click to play):</p>
		</div>
	</body>
</html>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/sizing.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>OpenTok Sample &#8212; Video Sizing</title>
	<link href="http://static.opentok.com/opentok/assets/css/demos.css" type="text/css" rel="stylesheet" >
	<script src="http://static.opentok.com/v1.1/js/TB.min.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript">
		var apiKey = "22232342"; // Replace with your API key. See https://dashboard.tokbox.com/projects
		var sessionId = "<%= @room.sessionId %>"; // Replace with your own session ID. See https://dashboard.tokbox.com/projects
		var token = "<%= @tok_token %>"; // Replace with a generated token. See https://dashboard.tokbox.com/projects
		var session;
		var publisher;

		var PUBLISHER_WIDTH = 220;
		var PUBLISHER_HEIGHT = 165;
		var subscriber_width = [120, 160, 220];
		var subscriber_height = [90, 120, 165];

		// Un-comment either of the following to set automatic logging and exception handling.
		// See the exceptionHandler() method below.
		// TB.setLogLevel(TB.DEBUG);
		TB.addEventListener("exception", exceptionHandler);

		if (TB.checkSystemRequirements() != TB.HAS_REQUIREMENTS) {
			alert("You don't have the minimum requirements to run this application."
				  + "Please upgrade to the latest version of Flash.");
		} else {
			// Register the exception handler and
			// create the local session object
			session = TB.initSession(sessionId);

			// Add event listeners to the session
			session.addEventListener("sessionConnected", sessionConnectedHandler);
			session.addEventListener("streamCreated", streamCreatedHandler);
			session.addEventListener("streamDestroyed", streamDestroyedHandler);

			/*
			If testing the app from the desktop, be sure to check the Flash Player Global Security setting
			to allow the page from communicating with SWF content loaded from the web. For more information,
			see http://www.tokbox.com/opentok/build/tutorials/helloworld.html#localTest
			*/
			session.connect(apiKey, token);
		}

		//--------------------------------------
		//  OPENTOK EVENT HANDLERS
		//--------------------------------------

		function sessionConnectedHandler(event) {

			// Now possible to start streaming
			document.getElementById("status").innerHTML = 'You can start publishing.';
			show("publishLink");
		}

		function streamCreatedHandler(event) {

			// When we get a streamCreated event for the stream we publish,
			// build the grid of subscribers at the appropriate sizes.

			for (var i = 0; i < event.streams.length; i++) {
				if (event.streams[i].connection.connectionId == event.target.connection.connectionId) {
					// Our publisher just started streaming
					// Create sized grid of subscribers

					for (y = 0; y < 3; y++) {
						for (x = 0; x < 3; x++) {

							// Create a div for the subscriber to replace
							var parentDiv = document.getElementById("cell_" + x + "_" + y);
							var stubDiv = document.createElement("div");
							stubDiv.id = "opentok_subscriber_" + x + "_" + y;
							parentDiv.appendChild(stubDiv);

							var subscriberProps = {width: subscriber_width[x],
													height: subscriber_height[y],
													subscribeToAudio: false};
							event.target.subscribe(event.streams[i], stubDiv.id, subscriberProps);
						}
					}

					// Update status and controls
					document.getElementById('status').innerHTML = 'You are publishing.';
					show("unpublishLink");
				}
			}
		}

		function streamDestroyedHandler(event) {
			for (var i = 0; i < event.streams.length; i++) {
				if (event.streams[i].connection.connectionId == event.target.connection.connectionId) {
					// Our publisher just stopped streaming
					// Update status and controls
					document.getElementById("status").innerHTML = 'You can start publishing.';
					show("publishLink");
				}
			}
		}

		/*
		If you un-comment the call to TB.addEventListener("exception", exceptionHandler) above, OpenTok calls the
		exceptionHandler() method when exception events occur. You can modify this method to further process exception events.
		If you un-comment the call to TB.setLogLevel(), above, OpenTok automatically displays exception event messages.
		*/
		function exceptionHandler(event) {
			alert("Exception: " + event.code + "::" + event.message);
		}

		//--------------------------------------
		//  LINK CLICK HANDLERS
		//--------------------------------------

		// Called when user wants to start participating in the call
		function startPublishing() {
			// Starts publishing user local camera and mic
			// as a stream into the session

			// Create a div for the publisher to replace
			var parentDiv = document.getElementById("myCamera");
			var stubDiv = document.createElement("div");
			stubDiv.id = "opentok_publisher";
			parentDiv.appendChild(stubDiv);

			var publisherProps = {width: PUBLISHER_WIDTH, height: PUBLISHER_HEIGHT, publishAudio: false};
			publisher = TB.initPublisher(apiKey, stubDiv.id, publisherProps);
			session.publish(publisher);

			document.getElementById("status").innerHTML = "Initiating publishing...";
			hide("publishLink");
		}

		// Called when user wants to stop participating in the call
		function stopPublishing() {
			if (publisher) {
				// Stop the stream
				session.unpublish(publisher);
				publisher = null;
			}

			document.getElementById("status").innerHTML = "Ceasing publishing...";
			hide("unpublishLink");
		}

		//--------------------------------------
		//  HELPER METHODS
		//--------------------------------------

		function show(id) {
			document.getElementById(id).style.display = 'block';
		}

		function hide(id) {
			document.getElementById(id).style.display = 'none';
		}

		// Insert table formatting rules into the stylesheet
		function formatTable() {
			for (i = 0; i < 3; i++) {
				var headElement = document.getElementsByTagName("th")[2 * (i + 1) - 1]
				headElement.innerHTML = subscriber_width[i] + ' px';
				for (j = 0; j < 3; j++) {
					var rowTitleElement = document.getElementById("row_title_" + j);
					rowTitleElement.innerHTML = subscriber_height[j] + ' px';
					var tableCell = document.getElementById("cell_" + i + "_" + j)
					tableCell.style.width = subscriber_width[i] + 'px';
					tableCell.style.height = subscriber_height[j] + 'px';
				}
			}
			show("subscribers");
		}
	</script>
	<style type="text/css">
#videobar {
			padding: 20 10 20 10;
		}
#localview {
			float: left;
			width: 240px;
			height: 265px;
		}
		div.section {
			font-weight: bold;
			font-size: 18px;
			margin: 15 0 8 0;
		}
		div.description {
			margin: 8 0 0 0;
		}
#subscribers {
			display:none;
}
#action, #status {
			font-size: 80%;
			margin-top: 10px;
		}
		table {
			border-style: none;
			border-collapse: collapse;
			font-size: 90%;
		}
		td {
			border-width: 1px;
			border-collapse: collapse;
			border-color: gray;
			border-style: solid;
			padding: 0;
		}
		th {
			font-weight: normal;
			height: 30px;
			vertical-align: bottom;
			border-width: 1px;
			padding: 0 0 5 0;
			border-collapse: collapse;
			border-color: gray;
			border-style: solid;
			border-top: none;
		}
		th.row-title, td.row-title {
			width: 50px;
			text-align: right;
			padding-right: 8px;
			border-left: none;
		}
		td.subscriber {
			vertical-align: middle;
			text-align: center;
		}
		td.column-spacer {
			width: 12px;
		}
		tr.row-spacer {
			height: 9px;
		}

	</style>
</head>
<body onload="formatTable()">
	<div id="videobar" class="videobar">
		<div id="localview">
			<div id="status" class="smalltype">Connecting</div>
			<div id="action" class="smalltype">
		       	<input type="button" value="Start Publishing" id ="publishLink" onClick="javascript:startPublishing()" />
		       	<input type="button" value="Stop Publishing" id ="unpublishLink" onClick="javascript:stopPublishing()" />
			</div>
			<div id="myCamera" class="publisherContainer"></div>
		</div>
		<div id="subscribers">
			<table>
				<tr class="column-title">
					<th class="row-title"></th>
					<th class="column_0"></th>
					<th class="column-spacer"></th>
					<th class="column_1"></th>
					<th class="column-spacer"></th>
					<th class="column_2"></th>
				</tr>
				<tr class="row_0">
					<td class="row-title" id="row_title_0"></td>
					<td id="cell_0_0" class="subscriber"></td>
					<td class="column-spacer"></td>
					<td id="cell_1_0" class="subscriber"></td>
					<td class="column-spacer"></td>
					<td id="cell_2_0" class="subscriber"></td>
				</tr>
				<tr class="row-spacer">
					<td class="row-title"></td><td></td><td></td><td></td><td></td><td></td>
				</tr>
				<tr class="row_1">
					<td class="row-title" id="row_title_1"></td>
					<td id="cell_0_1" class="subscriber"></td>
					<td class="column-spacer"></td>
					<td id="cell_1_1" class="subscriber"></td>
					<td class="column-spacer"></td>
					<td id="cell_2_1" class="subscriber"></td>
				</tr>
				<tr class="row-spacer">
					<td class="row-title"></td><td></td><td></td><td></td><td></td><td></td>
				</tr>
				<tr class="row_2">
					<td class="row-title" id="row_title_2"></td>
					<td id="cell_0_2" class="subscriber"></td>
					<td class="column-spacer"></td>
					<td id="cell_1_2" class="subscriber"></td>
					<td class="column-spacer"></td>
					<td id="cell_2_2" class="subscriber"></td>
				</tr>
			</table>
		</div>
	</div>
	</body>
</html>